language: python
python:
  - '3.6'
install:
  - pip install sphinx sphinx_rtd_theme
script:
  - ./build.sh
deploy:
  - provider: s3
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: 'www.scalabel.ai'
    skip_cleanup: true
    acl: public_read
    region: us-west-2
    local_dir: _doc
    upload-dir: doc
    exclude: ".DS_Store"
    on:
      branch: master
