deploy:
  provider: s3
  access_key_id: "AKIAIW2IGWIEMPAME62A"
  secret_access_key: secret_access_key
  bucket: "S3 Bucket"
  skip_cleanup: true
  acl: public_read
  region: us-west-2
  upload-dir: www.scalabel.ai
  on:
    branch: master
