language: python
python:
- '3.6'
install:
- pip install sphinx sphinx_rtd_theme
script:
- make html
deploy:
  - provider: s3
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: 'test-www.scalabel.ai'
    skip_cleanup: true
    acl: public_read
    region: us-west-2
    local_dir: _build/html
    upload-dir: doc
    exclude: ".DS_Store"
    on:
      branch: auto_deploy
  - provider: s3
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: 'test-www.scalabel.ai'
    skip_cleanup: true
    acl: public_read
    region: us-west-2
    local_dir: instructions
    upload-dir: doc/instructions
    exclude: ".DS_Store"
    on:
      branch: auto_deploy
  - provider: s3
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: 'test-www.scalabel.ai'
    skip_cleanup: true
    acl: public_read
    region: us-west-2
    local_dir: demo
    upload-dir: doc/demo
    exclude: ".DS_Store"
    on:
      branch: auto_deploy
